package com.finanscore.credit.messaging;
import com.fasterxml.jackson.databind.ObjectMapper;import com.finanscore.contracts.*;import com.finanscore.credit.domain.*;import com.finanscore.credit.infrastructure.*;import com.finanscore.support.idempotency.*;import com.finanscore.support.observability.ObservabilityContext;import com.finanscore.support.outbox.*;import io.opentelemetry.instrumentation.annotations.WithSpan;import org.springframework.kafka.annotation.KafkaListener;import org.springframework.stereotype.Component;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Component public class CreditWorkflowConsumer{private final ObjectMapper om;private final CreditRequestRepository repo;private final IdempotentEventGuard guard;private final OutboxService outbox;public CreditWorkflowConsumer(ObjectMapper o,CreditRequestRepository r,IdempotentEventGuard g,OutboxService b){om=o;repo=r;guard=g;outbox=b;}private EventEnvelope e(String raw)throws Exception{return om.readValue(raw,EventEnvelope.class);}private UUID id(EventEnvelope e){return UUID.fromString(String.valueOf(e.payload().get("requestId")));}
 @WithSpan("process-payment-validated") @KafkaListener(topics=EventTopics.PAYMENT_VALIDATED,groupId="credit-payment-validated") @Transactional public void paymentOk(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){if(guard.alreadyProcessed(e.eventId(),"credit-payment-validated"))return;var x=repo.findById(id(e)).orElseThrow();if(!x.userId.equals(Long.valueOf(String.valueOf(e.payload().get("userId")))))throw new IllegalStateException("Usuario de pago no coincide");x.status=CreditRequestStatus.SCORING_IN_PROGRESS;x.updatedAt=Instant.now();repo.save(x);Map<String,Object> p=new LinkedHashMap<>();p.put("requestId",x.id.toString());p.put("userId",x.userId);p.put("productCode",x.productCode);p.put("amount",x.amount);p.put("currency",x.currency);p.put("termMonths",x.termMonths);p.put("purpose",x.purpose);outbox.append("CreditEvaluationRequested",x.id.toString(),x.correlationId,e.eventId(),null,"credit-service",p);guard.markProcessed(e.eventId(),"credit-payment-validated");}}
 @WithSpan("process-payment-rejected") @KafkaListener(topics=EventTopics.PAYMENT_REJECTED,groupId="credit-payment-rejected") @Transactional public void paymentRejected(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){if(guard.alreadyProcessed(e.eventId(),"credit-payment-rejected"))return;var x=repo.findById(id(e)).orElseThrow();x.status=CreditRequestStatus.PAYMENT_REJECTED;x.updatedAt=Instant.now();repo.save(x);guard.markProcessed(e.eventId(),"credit-payment-rejected");}}
 @WithSpan("process-scoring-result") @KafkaListener(topics=EventTopics.SCORING_CALCULATED,groupId="credit-scoring-result") @Transactional public void scoring(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){if(guard.alreadyProcessed(e.eventId(),"credit-scoring-result"))return;var x=repo.findById(id(e)).orElseThrow();x.status=CreditRequestStatus.REPORT_GENERATING;x.scoreValue=Integer.valueOf(String.valueOf(e.payload().get("score")));x.recommendation=String.valueOf(e.payload().get("recommendation"));x.modelVersion=String.valueOf(e.payload().get("modelVersion"));x.updatedAt=Instant.now();repo.save(x);guard.markProcessed(e.eventId(),"credit-scoring-result");}}
 @WithSpan("process-report-result") @KafkaListener(topics=EventTopics.REPORT_GENERATED,groupId="credit-report-result") @Transactional public void report(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){if(guard.alreadyProcessed(e.eventId(),"credit-report-result"))return;var x=repo.findById(id(e)).orElseThrow();x.status=CreditRequestStatus.NOTIFICATION_PENDING;x.reportId=UUID.fromString(String.valueOf(e.payload().get("reportId")));x.updatedAt=Instant.now();repo.save(x);guard.markProcessed(e.eventId(),"credit-report-result");}}
 @WithSpan("process-notification-result") @KafkaListener(topics=EventTopics.NOTIFICATION_SENT,groupId="credit-notification-result") @Transactional public void notified(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){if(guard.alreadyProcessed(e.eventId(),"credit-notification-result"))return;var x=repo.findById(id(e)).orElseThrow();x.status=CreditRequestStatus.COMPLETED;x.updatedAt=Instant.now();repo.save(x);guard.markProcessed(e.eventId(),"credit-notification-result");}}
 @WithSpan("process-workflow-dlt") @KafkaListener(topics={EventTopics.PAYMENT_VALIDATED+".DLT",EventTopics.CREDIT_EVALUATION_REQUESTED+".DLT",EventTopics.SCORING_CALCULATED+".DLT",EventTopics.REPORT_GENERATED+".DLT",EventTopics.NOTIFICATION_SENT+".DLT"},groupId="credit-workflow-dlt") @Transactional public void workflowFailed(String raw)throws Exception{var e=e(raw);try(var ignored=ObservabilityContext.bind(e)){var requestId=id(e);var x=repo.findById(requestId).orElse(null);if(x==null)return;x.status=CreditRequestStatus.FAILED;x.updatedAt=Instant.now();repo.save(x);}}
}
