#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/secrets/bootstrap.env"
mkdir -p "$ROOT/secrets"
if [[ -f "$OUT" && "${1:-}" != "--force" ]]; then
  echo "$OUT ya existe. Use --force para regenerarlo."
  exit 0
fi
secret(){ openssl rand -hex 24; }
id(){ openssl rand -hex 16; }
{
  echo '# Generado localmente. NO VERSIONAR. V3.6'
  for n in POSTGRES_SUPER_PASSWORD IAM_DB_PASSWORD CREDIT_DB_PASSWORD PAYMENT_DB_PASSWORD SCORING_DB_PASSWORD REPORT_DB_PASSWORD NOTIFICATION_DB_PASSWORD AUDIT_DB_PASSWORD QUERY_DB_PASSWORD DEV_CERT_PASSWORD KAFKA_ADMIN_PASSWORD KAFKA_BROKER_PASSWORD KAFKA_IAM_PASSWORD KAFKA_CREDIT_PASSWORD KAFKA_PAYMENT_PASSWORD KAFKA_SCORING_PASSWORD KAFKA_REPORT_PASSWORD KAFKA_NOTIFICATION_PASSWORD KAFKA_AUDIT_PASSWORD KAFKA_QUERY_PASSWORD KAFKA_SCHEMA_REGISTRY_PASSWORD REDIS_PASSWORD MINIO_ROOT_PASSWORD GRAFANA_ADMIN_PASSWORD IAM_DEMO_PASSWORD IAM_ADMIN_PASSWORD OAUTH2_NOTIFICATION_CLIENT_SECRET VAULT_DEV_ROOT_TOKEN_ID; do
    echo "$n=$(secret)"
  done
  echo 'GOOGLE_CLIENT_SECRET='
  echo 'TIKTOK_CLIENT_SECRET='
  echo 'GMAIL_APP_PASSWORD='
  for s in IAM CREDIT PAYMENT SCORING REPORT NOTIFICATION AUDIT QUERY; do
    echo "VAULT_${s}_ROLE_ID=$(id)"
    echo "VAULT_${s}_SECRET_ID=$(secret)"
  done
} > "$OUT"
chmod 600 "$OUT" || true
echo "Secretos locales generados en $OUT"
